apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserverns
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-167.172.6.138.nip.io
---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserverns
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=

