apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dovns
commonLabels: 
  env: dev

replicas:
  - name: dov-po-deployment
    count: 1

images:
  - name: chukmunnlee/dov-bear
    newTag: v5


configMapGenerator:
  - name: dov-cm
    literals:
      - INSTANCE_NAME="my dov bear"

patches:
  - target:
      kind: Ingress
      name: dov-ing
    path: patches.yaml


