apiVersion: skaffold/v4beta6 latest
kind: Config
metadata:
  name: dov-bear

build:
  artifacts:
    - image: chukmunnlee/sk-dov-bear
      context: .
      docker: 
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: false
  platforms:
    - linux/amd64
    - darwin/ard64

manifests:
  kustomize:
    paths:
    - .

deploy:
  kubectl:
    flags:
      delete:
      - --force
      - --grace-period=0

portForward:
  - resourceType: Service
    resourceName: dev-dov-svc
    port: 8080
    localPort: 3000