# Stage 1
FROM node:17-alpine as builder

# set working directory
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
COPY . . 
RUN npm run build


# Stage 2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build . 
COPY nginx.conf /etc/nginx/nginx.conf
# EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]